### ISSUE TITLE
Erro ao executar o chonosServer no ubuntu 22.04

### ISSUE THREAD

**Issue by souzavdj** [chon-group/contextNetServer#1]
Segue um print do meu terminal com o erro.
![print do erro](https://github.com/chon-group/contextNetServer/assets/23249901/50a4e5f6-6689-420c-972b-ee6724516082)

**Comment by nilsonLazarin** [comment]
Hi @souzavdj,
Bug solved. Thank you for sharing!

![image](https://github.com/chon-group/contextNetServer/assets/32855001/981d45d2-16fb-45b8-b1b6-4c77602e4825)
